--- Makefile	2015-08-19 06:55:31.369984144 +0700
+++ Makefile_new	2015-08-19 06:56:13.343484304 +0700
@@ -81,7 +81,8 @@
 io: libxcmd libhandle
 quota: libxcmd
 repair: libxlog
-
+libxlog: libxfs
+libxlog-install-dev: libxfs-install-dev
 
 ifeq ($(HAVE_BUILDDEFS), yes)
 include $(BUILDRULES)
